### ISSUE TITLE
BOOTSTRAP_MPI 

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#1]
Was set at 40 hard in the code and at 100 in the constants file. The constants.BOOTSTRAP_MPI was never used. Hayssam has set it at 40. This is how it should be in the json config now (and not 100).

**Comment by tigloo123** [comment]
@ben : est-ce résolu ?

**Comment by bdartigues** [comment]
Issue resolved BOOTSTRAP MPI is set to 40 in config file
