### ISSUE TITLE
cytoplasmic_total_count

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#10]
Insert correct figure numbers (in comments) in cytoplasmic_total_count.py. 
Make sure that all cytoplasmic count figures are generated by this script (and nothing extra)

**Comment by bdartigues** [comment]
Script has been cleaned, correct figures number has been added and code has been restructured like MTOC analysis

**Comment by bdartigues** [comment]
see branch cytoplasmic_total_count_issue_10

**Comment by ebouilhol** [comment]
Starting test

**Comment by ebouilhol** [comment]
Unit test are OK
Two figures are missing in this branch : 

mrna_cytoplasmic_total_count.png
protein_cytoplasmic_total_count.png

Not merging yet.
