### ISSUE TITLE
cytoplasmic spread

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#11]
Check all the python scripts for correct information on figure numbers in analysis/cytoplasmic_spread/
Make sure that all the necessary figures are generated and nothing extra

**Comment by bdartigues** [comment]
see cytoplasmic_spread_issue11

**Comment by ebouilhol** [comment]
Starting test

**Comment by ebouilhol** [comment]
Unit test OK
Figures OK

merging with branch master and closing issue.
