### ISSUE TITLE
peripheral_fraction_profile.py

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#12]
This code needs cleanup:
-  get rid of all the commented dead code
- check whether all the necessary figures are generated and correctly named in the comments
- no extra figures should be produced 
- keep only the necessary configuration files

**Comment by bdartigues** [comment]
get rid of all the commented dead code => done
    check whether all the necessary figures are generated and correctly named in the comments => done
    no extra figures should be produced => done
    keep only the necessary configuration files => done
