### ISSUE TITLE
muscle: move to analysis config

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#14]
Such things have to go to the analysis config file
https://github.com/cbib/dypfish/blob/a4660a389ef7883cc79360d1a884f72e760325d0/src/analysis/muscle/density_analysis.py#L26

**Comment by tigloo123** [comment]
Same here : https://github.com/cbib/dypfish/blob/a4660a389ef7883cc79360d1a884f72e760325d0/src/analysis/muscle/density_analysis.py#L25

**Comment by bdartigues** [comment]
Adding constants for band_n (STRIPE_NUM) and genes (MRNA_GENES_LABEL). See branch muscle_figures_name

**Comment by ebouilhol** [comment]
Solved with muscle_figures_name
