### ISSUE TITLE
muscle: missing comments and logger printing

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#15]
Add in the comments figure numbers and add logger printing as for the other scripts

**Comment by massyah** [comment]
cf https://github.com/cbib/dypfish/blob/eb78c757d726fcf5fa0115596a17b30e847f4976/src/analysis/muscle/compute_z_line_distance.py#L41-L45

**Comment by bdartigues** [comment]
Adding comments figure numbers and logger printing as for the other scripts. See branch muscle_figures_name

**Comment by ebouilhol** [comment]
Closed with muscle_figures_name
