### ISSUE TITLE
cleanup the non-python style comments

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#16]
Here:
https://github.com/cbib/dypfish/blob/a4660a389ef7883cc79360d1a884f72e760325d0/src/analysis/spots_density/compare_cell_characteristics.py#L21

and everywhere else

**Comment by bdartigues** [comment]
Cleaning the non-python style comments - See branch spots_density

**Comment by ebouilhol** [comment]
Starting tests

**Comment by ebouilhol** [comment]
Tests OK, figures OK, merging and closing branch spot_density
