### ISSUE TITLE
stability_peripheral_fraction.py

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#18]
Comment the figure number
Restructure the code

**Comment by massyah** [comment]
cf https://github.com/cbib/dypfish/blob/eb78c757d726fcf5fa0115596a17b30e847f4976/src/analysis/stability/stability_peripheral_fraction.py#L44-L50

**Comment by bdartigues** [comment]
-Figures are correctly commented. 
-Code has been cleaned-up and restrustured. 
-See branch stability_analysis_figures_name

**Comment by bdartigues** [comment]
See branch stability_analysis_figures_name

**Comment by ebouilhol** [comment]
Starting test

**Comment by ebouilhol** [comment]
Unit tests are OK

The figure is almost good, the main difference is on the x-axis, on the original figure the black line stop at 22, when the blue one stop at 38. Here we have 100 for the black line, 200 for the blue line.

![stability_peripheral_fraction_original](https://user-images.githubusercontent.com/4415638/88561797-279f9980-d030-11ea-83ae-7fcdff37ba7c.png)

**Comment by bdartigues** [comment]
Yes this is due to an higher number of cells included in the code when loading image set. We can remove some timepoints but i remember that the figure is not the same if we do that. using timepoint 3h only for cultured and micropatterned makes the blue line over the black line.
