### ISSUE TITLE
dead code or issue with running the temporal_interactions.py script

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#22]
If this is dead code, please remove
Otherwise make it run without need for uncommenting

https://github.com/cbib/dypfish/blob/a4660a389ef7883cc79360d1a884f72e760325d0/src/analysis/temporal_interactions/temporal_interactions.py#L158

**Comment by tigloo123** [comment]
Make sure that all the necessary computations for the paper are still performed after removing the dead code
Indicate in a comment that the generated figure is different from the paper

**Comment by bdartigues** [comment]
remove dead code or issue from temporal_interactions.py
see commit https://github.com/cbib/dypfish/commit/5807c39b469e8a96bf4f19a7b22daf35897b6619
