### ISSUE TITLE
dead code cleanup in volume_corrected.py

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#23]
Why these lines are here: either remove or make it run cleanly (without need for uncommenting)
https://github.com/cbib/dypfish/blob/a4660a389ef7883cc79360d1a884f72e760325d0/src/analysis/volume-corrected-noise-measure/volume_corrected.py#L28

**Comment by bdartigues** [comment]
this is the 3D computation. given that we used 2D, probably remove this piece of code

**Comment by bdartigues** [comment]
Only 3D computation has been kept
Figures are corretly labelled
Fix in branch volume_corrected_noise_measure_issue_23

**Comment by ebouilhol** [comment]
Fixed in merge of volume_corrected_noise_measure_issue_23
