### ISSUE TITLE
MultiNucleus class

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#25]
Check whether this is needed or is it a superfluous class subdivision?
https://github.com/cbib/dypfish/blob/a4660a389ef7883cc79360d1a884f72e760325d0/src/image.py#L650

**Comment by ebouilhol** [comment]
Will check

**Comment by ebouilhol** [comment]
There is a few functions that are specific to this class, there is a lot of classes, this one does not look more superfluous than others.
