### ISSUE TITLE
Degree of clustering dynamic profiles are missing from new release 

### ISSUE THREAD

**Issue by massyah** [cbib/dypfish#29]
The analysis was here in the previous version : 

https://github.com/cbib/dypfish/blob/a40e17b6d7b9d1bc2b4845c41e892c56be253307/analysis/degree_of_clustering/main.py#L27-L33

**Comment by massyah** [comment]
Same for protein based analysis, it's missing from latest version

**Comment by bdartigues** [comment]
The analysis is now handled by degree_of_clustering_timepoints.py as requested in issue #8
