### ISSUE TITLE
Statistical interpretation of the error bars in bar plots

### ISSUE THREAD

**Issue by massyah** [cbib/dypfish#30]
The bar plots with error bars, mostly used in the degree of clustering analysis, are difficult to interpret. The essence of the computation is 
```
            m = median(X)
            mad = scipy.stats.median_absolute_deviation(X)
            bar_height = math.log(m) - base
            err = math.log(m + mad) - math.log(m) - base

```

The data are generated by this code : 

https://github.com/cbib/dypfish/blob/a40e17b6d7b9d1bc2b4845c41e892c56be253307/analysis/chx/degree_of_clustering.py#L42-L57

and then plotted using this code : 

https://github.com/cbib/dypfish/blob/a40e17b6d7b9d1bc2b4845c41e892c56be253307/src/plot.py#L113-L131

(This code was in the previous version of the framework, it has not been migrated to the new version yet)

Some observations: 
* The line 
https://github.com/cbib/dypfish/blob/a40e17b6d7b9d1bc2b4845c41e892c56be253307/src/plot.py#L128
actually put the focus on the error bar, which can be misleading since it hides the scale of the effect 

* This code is based on Jonathan's initial matlab code, which is 
```
function a_compare_degree_of_clustering
% Compares degree of clustering for all mrnas and profiles
% Relates to Fig. 2D and Supp Exp Procedures, Supp Notes 5-6

% precalculate degree of clustering data
addpath('helper_functions','../../dypFISH_data');
settings = data_settings;
% precalculate_dofClustering_data(settings);
load('associated_data/data_a','dofClust_mrna','dofClust_protein');

N_mrna = settings.N_mrna;
N_protein = settings.N_protein;

% calculate log medians and errors
median_mrna = zeros(1,N_mrna);
error_mrna = zeros(1,N_mrna);
median_protein = zeros(1,N_protein);
error_protein = zeros(1,N_protein);
for cGene = 1:N_mrna
    median_mrna(cGene) = log(median(dofClust_mrna{cGene}));
    err = mad(dofClust_mrna{cGene},1); % median absolute deviation 
    error_mrna(cGene) = log(median(dofClust_mrna{cGene}) + err);
end
for cGene = 1:N_protein
    median_protein(cGene) = log(median(dofClust_protein{cGene}));
    err = mad(dofClust_protein{cGene},1);
    error_protein(cGene) = log(median(dofClust_protein{cGene}) + err);
end

% display
genes = settings.genes_display;
cols = settings.cols;
close all;
figure(1);
base = log(0.5);
for cGene = 1:N_mrna
    errorbar(cGene,median_mrna(cGene)-base,0,...
        error_mrna(cGene)-median_mrna(cGene)-base,cols(cGene));
    hold on;
    bar(cGene,median_mrna(cGene)-base,'FaceColor',cols(cGene));
end
ylabel('log degree of clustering');
set(gca, 'XTick', 1:N_mrna, 'XTickLabel', genes);
title('mrnas');
figure(2);
base = log(0.01);
for cGene = 1:N_protein
    errorbar(cGene,median_protein(cGene)-base,0,...
        error_protein(cGene)-median_protein(cGene)-base,cols(cGene));
    hold on;
    bar(cGene,median_protein(cGene)-base,'FaceColor',cols(cGene));
end
ylabel('log degree of clustering');
set(gca, 'XTick', 1:N_protein, 'XTickLabel', {genes{1:4}});
title('proteins');
```

* the bulk of the error bars comprises of the `base` offset, rather than real dispersion:  the error bar is cannot be reduced to less than 0.69, 
* I can't come up with a statistical explanation of the absence of signif. differences between medians when the bar overlaps, it seems that the series must span  orders of magnitude before having non overlapping error bars, 
* in Jonathan version, the `base` parameter was ≠ between mRNA (log(0.5 ~= -0.69) and proteins (log(0.01) ~= -4.61 ),

**Comment by massyah** [comment]
As a message in a bottle, I've asked for some help on stackexchange : https://stats.stackexchange.com/questions/474114/help-understanding-error-bars-based-on-mad

**Comment by tigloo123** [comment]
This issue is not closed yet (even if it has "bug" label). I thought we had put in place a solution --> we should discuss this together and close it
