### ISSUE TITLE
degree_of_clustering.py crashes on CHX data

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#32]
This is the error:
  
File "/Users/macha/Projects/dypfish/NewCode/dypfish/src/image_set.py", line 231, in <listcomp>
    return [image.compute_degree_of_clustering() for image in self.images]
AttributeError: 'ImageWithIntensities' object has no attribute 'compute_degree_of_clustering'

**Comment by tigloo123** [comment]
Indeed, compute_degree_of_clustering is defined only for the class Image3dWithSpots. CHX data is intensities

**Comment by bdartigues** [comment]
Wait feed back for close this issue @ebouilhol @EdgarLefevre

**Comment by bdartigues** [comment]
3D and 2D computation has been tested for mRNA and 2D computation only for intensity data (we do not used the Raw tif images anymore). For CHX data, mRNA and protein are both IF data, 2D intensity data computation works. see branch degree_of_clustering_chx

**Comment by bdartigues** [comment]
see branch degree_of_clustering_chx

**Comment by ebouilhol** [comment]
Solved
