### ISSUE TITLE
Ripley-K is not implemented

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#34]
The only code that is there is for 3D mRNA data
No code for 2D
No code for intensities data

**Comment by bdartigues** [comment]
It was deleted when splitting image3D and image 2D. degree of clusteirng computation in 2D has been added for intensity data. We do not used 2D for mRNA but we can add it ?

**Comment by bdartigues** [comment]
ImageWithIntensities  and ImageWithspots classes has 2D ripley-k function for degree of clustering. 3D ripley k for protein is not available
