### ISSUE TITLE
compute_peripheral_intensitie

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#35]
This function computes something strange: image.ImageWithIntensities.compute_peripheral_intensitie

There is already a function compute_peripheral_intensities (as well as other similar functions)
Is it redundant? 

Moreover what does this mean:
cytoplasm_mask = self.get_peripheral_mask()

is this a bug or a misnamed variables? 

Also and English mistake in the function name

**Comment by bdartigues** [comment]
cytoplasm_mask = self.get_peripheral_mask() is a misnamed variable problem. english mistake was corrected. rename compute_peripheral_intensities in compute_peripheral_intensity_mask. these are two differents functions.

**Comment by bdartigues** [comment]
see commit https://github.com/cbib/dypfish/commit/d18f963cfe05c9536e84aebb17b3221c336300f0
