### ISSUE TITLE
Degree of clustering timepoint : change dynamic representation

### ISSUE THREAD

**Issue by bdartigues** [cbib/dypfish#45]

**Comment by bdartigues** [comment]
- Dynamic representationb is no longer using spline interpolation but bar plot. 
- See degree_of_clustering_timepoints

**Comment by ebouilhol** [comment]
Starting tests

**Comment by ebouilhol** [comment]
Unit Tests  : OK
Figures producted as expected.

I'm closing this and merging branch degree_of_clustering_timepoints with master
