### ISSUE TITLE
CHX : build figure 2G and S2D without base ponderation and good error bars

### ISSUE THREAD

**Issue by bdartigues** [cbib/dypfish#46]

**Comment by bdartigues** [comment]
CHX figures correctly produced. Remove base ponderation and compute standard error inplace. see branch degree_of_clustering_chx

**Comment by bdartigues** [comment]
see commit https://github.com/cbib/dypfish/commit/3f4592e680d4aa022a0ce51609ec75af8a653565

**Comment by bdartigues** [comment]
see branch degree_of_clustering_chx

**Comment by ebouilhol** [comment]
Starting test

**Comment by ebouilhol** [comment]
Unit test  : OK
The figures are generated and corrected as expected, I'm merging this branch with master
