### ISSUE TITLE
Temporal interactions figures name and axes

### ISSUE THREAD

**Issue by ebouilhol** [cbib/dypfish#48]
The temporal interaction figures generated by temporal_interactions.py for nocodazole and pard3 analysis have :

- 4 time point (2h, 3h, 5h, 7h) in the axis for only to values displayed (3h and 5h). The legend should display only 3h and 5h
- A mistake in the name ( modifications to do in the config files :   "FIGURE_NAME_FORMAT_TIS": "{gene}_arhgdia_nocodazole_TIS.png",)

**Comment by bdartigues** [comment]
mistake in name and axis label has been fixed. See pull request @ebouilhol

**Comment by bdartigues** [comment]
legend is display correctly (3h and 5h) and figure name was modified. see branch temporal_interactions
