### ISSUE TITLE
Temporal interactions values error

### ISSUE THREAD

**Issue by ebouilhol** [cbib/dypfish#49]
The figures generated by temporal_interactions.py for the nocodazole experiment do not exacty match the figures from the paper.

**Comment by bdartigues** [comment]
- Found that there a redundant normalization by cytoplasmic_density. remove normalization by cytoplasmic density in compute_density_per_quadrant_and_slices() for Image3dWithSpotsAndMTOC and Image3dWithIntensitiesAndMTOC. 
- Make a new computation to test if figures are still differing.

**Comment by bdartigues** [comment]
- Found that mean were used instead of median in previous version of dypfish
- Density per slice and quadrants seem to not be computed as in previous version.
