### ISSUE TITLE
Script to download and place all datasets from the accompanying website 

### ISSUE THREAD

**Issue by massyah** [cbib/dypfish#5]

**Comment by tigloo123** [comment]
The data/savulescu/ directory should only contain (i) the script to upload the data and (ii) the structure of subdirectories. These subdirectories should be empty. The script will populate the subdirectories with HDF5 files and the corresponding dataset configuration files.

**Comment by EdgarLefevre** [comment]
Two scripts were added, the first to download test data (download_data_test.sh) and the second to download the paper's data (download_data_paper.sh). 

Each script will download the data in `data` folder, unzip it and remove the zip files. 

The scripts are at the project's root.
