### ISSUE TITLE
Output of TIS original figures

### ISSUE THREAD

**Issue by ebouilhol** [cbib/dypfish#50]
Values for TIS original figures have changed and do not exactly match the figures in the paper.

**Comment by bdartigues** [comment]
Same as for #49 
- Found that there a redundant normalization by cytoplasmic_density. remove normalization by cytoplasmic density in compute_density_per_quadrant_and_slices() for Image3dWithSpotsAndMTOC and Image3dWithIntensitiesAndMTOC.
- Make a new computation to test if figures are still differing.

**Comment by bdartigues** [comment]
- Found that mean were used instead of median in previous version of dypfish
- Density per slice and quadrants seem to not be computed as in previous version.

**Comment by ebouilhol** [comment]
Starting test for this branch

**Comment by bdartigues** [comment]
> Starting test for this branch

@ebouilhol Not sure changing median instead of mean and remove double normalization had resolved the problem. it is better now when comparing figures but i think this is definitively a error in the computation in V0, so i don't how to deal with that ??

**Comment by ebouilhol** [comment]
Unit test results : 

```
----------------------------------------------------------------------
Ran 82 tests in 494.424s

OK (skipped=2)

```

**Comment by ebouilhol** [comment]
@bdartigues 
There is a useless print somewhere in the peripheral_temporal_interactions.py that prints hundreds of lines of numbers :
```
13
20 7
14
20 8
15
30 1
16
30 2
17
30 3
18
30 4
19
30 5
20
30 6
21
30 7
```

**Comment by ebouilhol** [comment]
@bdartigues 

Not sure why, but the branch temporal_interactions does no longer produce the TIS figures for **nocodazole**

**Comment by ebouilhol** [comment]
Unit tests are OK, 

The code is running without errors. 

There is still major differences to investigate in some figures : 

- pard3_TIS.png

- arhgdia_nocodazole_TIS.png

I let the branch open for further development, but I will rebase with master to be up to date.

**Comment by bdartigues** [comment]
erro has beeen found. When computing  stat from tis alcculator, given that ffor nocodazole and Pard" we only have 2 Timepoint, the TIS formula shifts from  tis = (12 - stat) / 3.0 to tis = (10 - stat) / 9.0.
