### ISSUE TITLE
"Old" subdirectories present in dypfish/data/savulescu

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#63]

**Comment by tigloo123** [comment]
This directory contains subdirectories such as old_chx etc. This should not be the case

**Comment by ebouilhol** [comment]
"Old" directories contains readme files
We have to decide : 
1- Do we keep them ?
2- If yes : Is it possible to keep them and still use the data download scripts ?

**Comment by ebouilhol** [comment]
Removed the folders and put the readmes under data/savulescu/ 
See commit 9b684fd381a7f6cfdfb36bc3e189609f6810b287
