### ISSUE TITLE
Code cleanup needed in mpi_calculator.py

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#64]
Some commented code needs cleanup in this file

**Comment by bdartigues** [comment]
Cleanup unused commented code in mpi_calculator.py; the removed commented line is : density_stats['MTOC ratio'] = density_stats.apply(lambda row: row['MTOC'] / row.filter(regex=('Non MTOC.*')).mean() if row.filter(regex=('Non MTOC.*')).mean() != 0 else 0.0, axis=1) and was applied to avoid zeros when computing remativ density for MTOC vs NON MTOC." see commit 3c2f39a => ready to close
