### ISSUE TITLE
Runtime error in degree_of_clustering: warning divide by zero

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#68]
Running from the command line:
src/analysis/degree_of_clustering/degree_of_clustering.py:29: RuntimeWarning: divide by zero encountered in log
  gene2error_degree_of_clustering[gene] = np.std(np.log(degree_of_clustering))/math.sqrt(len(degree_of_clustering))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/_methods.py:117: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)

**Comment by bdartigues** [comment]
On l'a jamais eu celle là. C'est encore sur la standard error et le mode de calcul..déprimant ce truc.. Par contre, avec quels jeux as-tu eu cette erreur  ? car comme je l'avais jamais eu avant..

**Comment by tigloo123** [comment]
It comes from the fact that image_set.compute_degree_of_clustering sometimes returns 0. And log(0) is not defined.

**Comment by tigloo123** [comment]
Should be resolved by merging the confidence_interval branch
