### ISSUE TITLE
Code redundancy compute_degree_of_clustering

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#69]
image.def compute_degree_of_clustering(self) and image3d.def compute_degree_of_clustering(self) have exactly the same code
Can this been cleaned up (depends on the class hierarchy)

**Comment by bdartigues** [comment]
In image.py and image3D.py following classes: "imageWithSpots", "imageWithIntensities", "image3DWithSpots", "image3D WithIntensities",  _compute_degree_of_clustering()_ function calls _get_clustering_indices()_ with a decorated pattern (i.e. decotarive function checks attribute exists else computes it). _compute_clustering_indices()_ has differents processing step depending on 2D or 3D images. We could probably remove  _compute_degree_of_clustering()_ for image3D class given that this class inherits from image classe but needs to be test.

    `@helpers.checkpoint_decorator(CLUSTERING_INDICES_PATH_SUFFIX, dtype=np.float)
   def get_clustering_indices(self):
        return self.compute_clustering_indices()

    def compute_degree_of_clustering(self) -> int:
        h_star = self.get_clustering_indices()
        return np.array(h_star[h_star > 1] - 1).sum()`
