### ISSUE TITLE
dataset readme files

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#7]
The subdirectories in data/savulescu/ currently contain useless READMEs. They have to be (i) formatted in a way that would make them useful (see what I have tried for the "original" subfolder) but in addition (ii) contain the correct information. Note that the current README for the "original" data is not correct in its content (discrepancy vs the HDF5 file on dypfish.org). Moreover we have to make the correspondence of this information and the Materials tables in the manuscript (which probably need a cleanup ?).

**Comment by bdartigues** [comment]
@ebouilhol This issue has been double checked; README files are currently in the git repository under the old_config data/. are they included in the data from dypfih.org ?

**Comment by ebouilhol** [comment]
Readme have been formatted
