### ISSUE TITLE
degree of clustering script incomplete

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#8]
The script degree_of_clustering.py has to produce ALL the degree of clustering figures in the manuscript.
They are:  2F (original), 4B (prrc2c) and S2D  (CHX)
This script should be written in a similar fashion to mtoc_analysis.py
There should be an additional script degree_of_clustering_timepoints.py to produce the figures for the panel 2D

Additionally: double check if these are the only figures for the degree of clustering and if some are missing, add them.

**Comment by bdartigues** [comment]
Script is now written in similar fashion as mtoc_analysis.
Figures are 2E (original), 2F (dynamic original), 4B (prrc2c), 2G (CHX protein), S2D (CHX mRNA)
Additional script degree_of_clustering_timepoints.py has been added to produce figures 2F (dynamic original)

**Comment by bdartigues** [comment]
see commit https://github.com/cbib/dypfish/commit/4bae7fc9324b01263192002272f26883b0c47f61
