### ISSUE TITLE
Why are there 2 divisions by np.sum(IF[cell_mask == 1]

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#81]
https://github.com/cbib/dypfish/blob/c3d854215c287756ff8b5a61f70384a4b4d88a1b/src/image3d.py#L852

**Comment by bdartigues** [comment]
it is surely an error...  double copy code. it makes no sense to divide twice;

**Comment by bdartigues** [comment]
In this part of the analysis, we computed the IF relative density signal in each quadrant and slice (24 in total). Then we normalized the quadrant_slice density by the quadrant density. And finally we normalized once again by the cytoplasmic density. We probably do not need to normalized by cytoplasmic density given that quadrant_slice densities are already normalized by quadrant densities; What do you think ?

**Comment by bdartigues** [comment]
There is. clearly a wrong compuation. we also divide by the peripheral density at the end in compute_peripheral_normalized_quadrant_and_slice_densities() [image_set.py 314]. In total, we normalized four times !!!

**Comment by tigloo123** [comment]
Will be solved after merge with colocalization_following_issue_78

**Comment by bdartigues** [comment]
solved after merge with colocalization_following_issue_78
