### ISSUE TITLE
compute_clustering_indices: RipleyK 3D uses a different version of cell volume from the rest of the code

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#83]
The normalisation factor is computed as :

cell_mask_slices = self.get_cell_mask_slices()
nuw = np.sum(cell_mask_slices == 1) * pixels_in_slice

which is supposed to represent the cell volume
However this is very different from self.get_cell_volume() that is used elsewhere

**Comment by tigloo123** [comment]
This probably goes together with the z-coordinate multiplied by pixels_in_slice in the ripley_k_point_process function

**Comment by bdartigues** [comment]
This is the jonathan code that we reproduce and get_cell_volume() function has been changed in the meantime. The original volume computation was based on this. This goes with the z-coordinates in the ripley k. So the computation is not bugged at all but can be standardized as we did for other analysis.

**Comment by bdartigues** [comment]
solved after merge with colocalization_following_issue_78
