### ISSUE TITLE
compute_histogram_spots_peripheral_fraction not tested

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#84]

**Comment by tigloo123** [comment]
Renaming this function to 'compute_spots_fractions_per_isoline' in the colocalization_following_issue_78 branch

**Comment by tigloo123** [comment]
Also adding a test. Should be resolved after merge with branch colocalization_following_issue_78

**Comment by tigloo123** [comment]
build_mrna_peripheral_fraction_profiles needs a check now

**Comment by bdartigues** [comment]
function has been tested and merge with branch colocalization_following_issue_78 . Test has also been added with test_compute_cytoplasmic_spots_fractions_per_periphery() in testImageSet
