### ISSUE TITLE
degree of clustering configuration files 

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#9]
Currently the script  degree_of_clustering.py  refers to an non existing file src/analysis/degree_of_clustering/config_nocodazole.json

On the other hand configuration files necessary to produce certain  degree of clustering figures are missing

**Comment by bdartigues** [comment]
- Configuration files necessary to produce certain degree of clustering figures has been added.
- Reference to non existing file has been removed

**Comment by bdartigues** [comment]
See branch degree_of_clustering_issue_9

**Comment by ebouilhol** [comment]
Solved with degree_of_clustering_issue_9
