### ISSUE TITLE
MTOC analysis peripheral original error

### ISSUE THREAD

**Issue by bdartigues** [cbib/dypfish#92]
In mtoc_analysis, l.39, the following line: 

            non_mtoc_quadrants = res[res[:,1] == 0][:, 0].reshape(num_images, quadrants_num-1)

raises the error below:

```
Traceback (most recent call last):
  File "src/analysis/mtoc/mtoc_analysis.py", line 93, in <module>
    peripheral_flag=peripheral_flag)
  File "src/analysis/mtoc/mtoc_analysis.py", line 40, in compute_density_per_quadrant
    non_mtoc_quadrants = res[res[:,1] == 0][:, 0].reshape(num_images, quadrants_num-1)
ValueError: cannot reshape array of size 266 into shape (76,3)

```

**Comment by bdartigues** [comment]
Normally we should have 76 values for MTOC quadrant and 228 for non MTOC. here we got 266 alues for non MTOC. probably something to seee with 228 + 76/2 = 266

**Comment by tigloo123** [comment]
If precomputed quadrants are the wrong shape: e.g. fine-grained quantisation instead of 4 quadrants, this can happen. This means that the secondary.h5 has to be recomputed. Added an assertion so that the code fails with the correct error message in compute_normalised_quadrant_densities

**Comment by bdartigues** [comment]
Problem solved in new compute_normalised_quadrant_densities() function. assert check right number of quadrants * stripes values
