### ISSUE TITLE
comments cleanup needed

### ISSUE THREAD

**Issue by tigloo123** [cbib/dypfish#97]
Figure numbers have changed in the analysis scripts.
Some obsolete comments are present. For exemple:
src/analysis/degree_of_clustering/degree_of_clustering.py: Figure 2E left panel: plots the log mRNA degree of clustering normalized by log(0.5) for original

(possibly others)

**Comment by bdartigues** [comment]
All comments have been removed and all figures text have been updated. Solved in https://github.com/cbib/dypfish/commit/e97a62995308d724b5b86029203bb0c59fc0cfca
