### ISSUE TITLE
MTOC - Prrc2c pheripheral calculation

### ISSUE THREAD

**Issue by ebouilhol** [cbib/dypfish#98]
In mpi_calculator.py line 85
`adjusted_mtoc = mtoc - np.median(quadrants)  `

Calculations must use np.mean instead of np.median for peripheral prrc2c

**Comment by bdartigues** [comment]
A hack has been added to check wether it is prrc2c analysis and use np.mean consequently
solved in commit https://github.com/cbib/dypfish/commit/5aebbd5be23b6686be391902d4d9492bf602d345
